### ISSUE TITLE
Onetime password never sent for first time login

### ISSUE THREAD

**Issue by taylor-schneider** [homanp/superagent#959]
### Description

I setup superagent following the official instructions for docker compose. As far as I can tell, all the containers are up and healthy. When I navigate to the superagent ui on port 3000 I am directed to a login page. 

In my chrome browser's developer console I see several errors being logged to console:

```
4511-f657f4cf8e3cb8de.js:1 
        
        
       GET https://cdn.segment.com/v1/projects/undefined/settings 404 (Not Found)
s @ 4511-f657f4cf8e3cb8de.js:1
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
(anonymous) @ 3012-e4b3f5820317be2b.js:1
(anonymous) @ 3012-e4b3f5820317be2b.js:1
(anonymous) @ 3012-e4b3f5820317be2b.js:1
a @ 3012-e4b3f5820317be2b.js:1
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
Promise.then (async)
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
t @ 4511-f657f4cf8e3cb8de.js:1
e @ 4511-f657f4cf8e3cb8de.js:1
e.load @ 4511-f657f4cf8e3cb8de.js:1
88894 @ layout-4ebe4bca5d62fb31.js:1
p @ webpack-6ac3a0383e983b72.js:1
21734 @ layout-4ebe4bca5d62fb31.js:1
p @ webpack-6ac3a0383e983b72.js:1
Promise.then (async)
65821 @ layout-4ebe4bca5d62fb31.js:1
p @ webpack-6ac3a0383e983b72.js:1
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
p.O @ webpack-6ac3a0383e983b72.js:1
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
u @ webpack-6ac3a0383e983b72.js:1
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
7864-7ad21a1a45d421eb.js:1 Cannot GET - Invalid path or write key provided.

window.console.error @ 7864-7ad21a1a45d421eb.js:1
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
Promise.catch (async)
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
(anonymous) @ 3012-e4b3f5820317be2b.js:1
(anonymous) @ 3012-e4b3f5820317be2b.js:1
(anonymous) @ 3012-e4b3f5820317be2b.js:1
a @ 3012-e4b3f5820317be2b.js:1
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
Promise.then (async)
(anonymous) @ 4511-f657f4cf8e3cb8de.js:1
t @ 4511-f657f4cf8e3cb8de.js:1
e @ 4511-f657f4cf8e3cb8de.js:1
e.load @ 4511-f657f4cf8e3cb8de.js:1
88894 @ layout-4ebe4bca5d62fb31.js:1
p @ webpack-6ac3a0383e983b72.js:1
21734 @ layout-4ebe4bca5d62fb31.js:1
p @ webpack-6ac3a0383e983b72.js:1
Promise.then (async)
65821 @ layout-4ebe4bca5d62fb31.js:1
p @ webpack-6ac3a0383e983b72.js:1
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
p.O @ webpack-6ac3a0383e983b72.js:1
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
u @ webpack-6ac3a0383e983b72.js:1
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
3082-3f70539c083c3de8.js:1 
        
        
       GET http://supabase-kong:8000/auth/v1/user net::ERR_NAME_NOT_RESOLVED
(anonymous) @ 3082-3f70539c083c3de8.js:1
to @ 3082-3f70539c083c3de8.js:1
tn @ 3082-3f70539c083c3de8.js:1
(anonymous) @ 3082-3f70539c083c3de8.js:2
_useSession @ 3082-3f70539c083c3de8.js:2
await in _useSession (async)
_getUser @ 3082-3f70539c083c3de8.js:2
(anonymous) @ 3082-3f70539c083c3de8.js:2
(anonymous) @ 3082-3f70539c083c3de8.js:2
tv @ 3082-3f70539c083c3de8.js:1
_acquireLock @ 3082-3f70539c083c3de8.js:2
getUser @ 3082-3f70539c083c3de8.js:2
await in getUser (async)
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
(anonymous) @ layout-4ebe4bca5d62fb31.js:1
ap @ fd9d1056-b2afde25d1be260b.js:9
aM @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
aR @ fd9d1056-b2afde25d1be260b.js:9
aO @ fd9d1056-b2afde25d1be260b.js:9
iB @ fd9d1056-b2afde25d1be260b.js:9
(anonymous) @ fd9d1056-b2afde25d1be260b.js:9
M @ 7864-7ad21a1a45d421eb.js:25
7864-7ad21a1a45d421eb.js:1 TypeError: Failed to fetch
    at 3082-3f70539c083c3de8.js:1:65295
    at to (3082-3f70539c083c3de8.js:1:70230)
    at tn (3082-3f70539c083c3de8.js:1:69974)
    at 3082-3f70539c083c3de8.js:2:12397
    at tw._useSession (3082-3f70539c083c3de8.js:2:11060)
    at async tw._getUser (3082-3f70539c083c3de8.js:2:12308)
    at async 3082-3f70539c083c3de8.js:2:12159
```

When I enter my email into the provided textbox and click "send password" button, nothing happens. I do not see any logs updating in the docker containers. In the chrome tab developer console, I see the following additional error pop up:

```
3082-3f70539c083c3de8.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
    at eY (3082-3f70539c083c3de8.js:1:66921)
    at eW (3082-3f70539c083c3de8.js:1:67209)
    at tw.signInWithOtp (3082-3f70539c083c3de8.js:2:6195)
    at async r (page-0610629ef99f6a95.js:1:1013)
    at async 9233-b74af8b6446aa700.js:1:20094
```

It appears there is a JS error that is not being caught and delivered to the UI.

### Steps to reproduce

1. Deploy super agent using docker compose instructions
2. Navigate to homepage of superagent
3. Enter email in textbox
4. Click "Send Password" button

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@taylor-schneider did you enable sending emails in Supabase? Did you check spam folder?

**Comment by taylor-schneider** [comment]
@homanp I did check the spam but did not see anything. In terms of enabling sending emails; can you be more specific. I did not set any email specific variables in the .env files, is that what you are referring to?

**Comment by taylor-schneider** [comment]
After grepping my configs, the two lines I think are relevant are:

```
./libs/.docker/ui/supabase/.env:60:ENABLE_EMAIL_SIGNUP=true
./libs/.docker/ui/supabase/.env:61:ENABLE_EMAIL_AUTOCONFIRM=true
```

**Comment by ssrheart425** [comment]
me too, have you solved it?
